### ISSUE TITLE
Package to more distributions

### ISSUE THREAD

**Issue by patri9ck** [patri9ck/a2ln-server#2]
Distribution | Packaged? | Maintainer
--------------- | --------------- | --------------
Arch Linux (AUR) | Yes | patri9ck
Debian / Ubuntu | No | -
Fedora | No | -
Void Linux | No | -

**Comment by beankylla** [comment]
Available to test the fedora package ☺️

**Comment by patri9ck** [comment]
Thanks for the effort! That would be great!

**Comment by luqmanishere** [comment]
> in case someone wants to help with packaging it for nixos (NUR for now): i have a half-working package: it starts, but for some reason the pairing times out without any error: https://github.com/Jan9103/nur-packages/blob/a2ln/pkgs/a2ln/default.nix.

The derivation you made works with v1.1.10, just make sure the firewall allows the pairing ports or is off alltogether. NixOS defaults to having the firewall on.

**Comment by beankylla** [comment]
i'm reading about all this packaging and wondering if flatpak is not an easier way to get this done?

**Comment by patri9ck** [comment]
Flatpak probably would be a good addition. Unfortunately, I don't have time to implement it by myself at the moment - at least it does not have a big priority for me with there being other installation methods like pip as mentioned before. It would be great if someone else maintained it or at least created a PR adding all the necessary meta files and a functioning build - then I could also maintain it considering future updates.

**Comment by joe733** [comment]
Hi @patri9ck, I can help containerizing the server. Which will run on all platforms with [podman](https://podman.io/) or [docker](https://www.docker.com/) or something similar. It also can be started on boot. With your permission, may I start working on it, in my spare time?

**Comment by patri9ck** [comment]
> Hi @patri9ck, I can help containerizing the server. Which will run on all platforms with [podman](https://podman.io/) or [docker](https://www.docker.com/) or something similar. It also can be started on boot. With your permission, may I start working on it, in my spare time?

Hey @joe733, sorry for the recent inactivity. Containerizing the server would be great to provide another option for users. Feel free to work on it!

**Comment by Alter-RK** [comment]
We really hope for the flatpak version or the app-image. It's a bit difficult to put the server on the same debian 13. Thank you for your work!

**Comment by octvs** [comment]
> The derivation you made works with v1.1.10, just make sure the firewall allows the pairing ports or is off alltogether. NixOS defaults to having the firewall on.

Is this still the case @luqmanishere? I have tried the derivation from your nix config with fw disabled to no avail:
```sh
Traceback (most recent call last):
  File "/nix/store/hir20ya35p2a3z0n5nglv06dyjawk280-a2ln-1.1.10/bin/..a2ln-wrapped-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nix/store/hir20ya35p2a3z0n5nglv06dyjawk280-a2ln-1.1.10/lib/python3.11/site-packages/a2ln/a2ln.py", line 67, in main
    zmq.auth.create_certificates(own_keys_directory, "server")
  File "/nix/store/vpgqa91mq2y6vb9ylchzcfmlpwgz2c0i-python3.11-pyzmq-25.1.2/lib/python3.11/site-packages/zmq/auth/certs.py", line 71, in create_certificates
    public_key, secret_key = zmq.curve_keypair()
                             ^^^^^^^^^^^^^^^^^^^
  File "zmq/backend/cython/utils.pyx", line 60, in zmq.backend.cython.utils.curve_keypair
  File "/nix/store/vpgqa91mq2y6vb9ylchzcfmlpwgz2c0i-python3.11-pyzmq-25.1.2/lib/python3.11/site-packages/zmq/error.py", line 149, in _check_rc
    raise ZMQError(errno)
zmq.error.ZMQError: Operation not supported
```
Previously I attributed the error to `pyzmq`, thus waited https://github.com/NixOS/nixpkgs/pull/294305 to land,  bumping its version `25.1.2`,  at the end it did not resolve the issue.
Cheers
