### ISSUE TITLE
Error in the code

### ISSUE THREAD

**Issue by T0F1Q2007** [patri9ck/a2ln-server#39]
Hi. I tried to download it automatically (pyhton pip) and manually. But I got the same issue at both of them.
`
Traceback (most recent call last):
  File "/usr/local/bin/a2ln", line 5, in <module>
    from a2ln import main
  File "/usr/local/lib/python3.11/dist-packages/a2ln/__init__.py", line 17, in <module>
    from .a2ln import main
  File "/usr/local/lib/python3.11/dist-packages/a2ln/a2ln.py", line 40, in <module>
    gi.require_version('Notify', '0.7')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 122, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Notify not available
`
Note: I'm using Kali Linux.

**Comment by T0F1Q2007** [comment]
I found the solution on the web. Simply on linux you need to run these commands:
`
apt show gir1.2-notify-0.7
sudo apt-get install gir1.2-notify-0.7
`
